 # A .ci.yml with the following declaration
 environment:
     vars: #These vars are exported as docker env variables
       BUNDLE_WITHOUT: production:development 
     language: ruby     # always single value   
    # image: rldevops/redis-server # Optional if repo has Dockerfile which would be used to  build an image
     services: rldevops/redis-server #list or single value 
       
       build:
  skip: true #skips build
  before: # single command or list of commands (run serially on each matrix job)
  - gem install -y rubygems-update
  - update_rubygems

  info: #print machine/environment diagnostics
  - bundle --version

  # single command or list of commands (run serially on each matrix job)
  #run: rake test
  # or as a hash map (each entry run in parallel in build matrix)
  run:         
    unit:        bundle exec rake spec:units
    integration: bundle exec rake spec:integration
    acceptance:  # Each parallelized step can also have multiple serial commands
    - bundle exec rake cucumber
    - bundle exec rake cucumber:javascript

  #starts a new build - initializes environment and  runs this script
  after: cap deploy staging

notifications: #list of notifications, notified ONLY on build fail and branch recovery.
  - email: srinivasiyerb@gmail.com
