environment:
   language: java
   services:
      - google/mysql



build:
    run: echo hello world

notifications: #list of notifications, notified ONLY on build fail and branch recovery.
  - email: srinivasiyerb@gmail.com
