 # A .ci.yml with the following declaration
    environment:
       language: ruby
       language_version: 1.9.3
    would call install_packages ruby-1.9.3
  function install_packages(){
    gemset=`echo ${PWD##*/} | tr ',' '_'`
    set +e
    if [[ $1 =~ "ree" ]]; then
      rvm use `echo $1 | sed -e "s/^ruby-//g" -e "s/_/-/g"`@$gemset --create
    elif [[ $1 =~ "jruby" ]]; then
      rvm use `echo $1 | sed -e "s/^ruby-//g" -e "s/_/-/g"`@$gemset --create
    else
      rvm use `echo $1 | sed -e "s/_/-/g"`@$gemset --create
    fi
    rvm gemset empty --force
    set -e
  }

notifications: #list of notifications, notified ONLY on build fail and branch recovery.
  - email: srinivasiyerb@gmail.com
